[0;32m[2025-08-04 12:03:07][0m === MLX Distributed Inference Launcher ===
[0;32m[2025-08-04 12:03:07][0m Timestamp: 20250804_120307
[0;32m[2025-08-04 12:03:07][0m Log directory: /Users/mini1/Movies/mlx_grpc_inference/logs
[0;32m[2025-08-04 12:03:07][0m Cleaning up existing processes...
[0;32m[2025-08-04 12:03:09][0m Configuring network...
[0;32m[2025-08-04 12:03:09][0m Setting MTU to 9000 on bridge0...
[1;33m[2025-08-04 12:03:09] WARNING:[0m Could not set MTU
[0;32m[2025-08-04 12:03:09][0m Testing SSH connectivity to 192.168.5.2...
SSH OK
mini2.local
Python 3.9.6
[0;32m[2025-08-04 12:03:09][0m âœ… SSH connectivity confirmed
[0;32m[2025-08-04 12:03:09][0m Testing basic MPI connectivity...
[0;32m[2025-08-04 12:03:09][0m Running basic MPI test...
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/mini1/Movies/mlx_grpc_inference/logs/test_mpi.py': [Errno 2] No such file or directory
--------------------------------------------------------------------------
prterun detected that one or more processes exited with non-zero status,
thus causing the job to be terminated. The first process to do so was:

   Process name: [prterun-mini1-78596@1,1]
   Exit code:    2
--------------------------------------------------------------------------
[0;32m[2025-08-04 12:03:10][0m âœ… Basic MPI test passed
[0;32m[2025-08-04 12:03:10][0m Setting up remote files on 192.168.5.2...
[0;32m[2025-08-04 12:03:10][0m Copying files to remote...
[0;32m[2025-08-04 12:03:11][0m Remote setup complete
[0;32m[2025-08-04 12:03:11][0m Launching with MPI backend over Thunderbolt...
[0;32m[2025-08-04 12:03:11][0m MPI Environment configured
[0;32m[2025-08-04 12:03:11][0m MPI launched with PID 78634
[0;32m[2025-08-04 12:03:11][0m Waiting for API server to start...
[mini1.local:78633] PRTE ERROR: Not found in file ess_hnp_module.c at line 443
